;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-kill-whole-line
        crux-move-beginning-of-line
        easy-kill
        emmet-expand-line
        helm-M-x
        indent-for-tab-command
        js2-line-break
        just-one-space-new
        kill-region
        kill-sexp
        kmacro-start-macro-or-insert-counter
        newline-without-break-of-line
        org-self-insert-command
        rjsx-delete-creates-full-tag
        sl/expand-indent-selection
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-up-sexp
        sp-delete-char
        sp-down-sexp
        sp-forward-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        typescript-insert-and-indent
        web-mode-fold-or-unfold
        ))

(setq mc/cmds-to-run-once
      '(
        goto-line
        helm-mini
        helm-projectile-ag
        kmacro-end-or-call-macro
        mark-whole-buffer
        mouse-set-region
        mouse-yank-primary
        sp-splice-sexp
        ))
